name: FD Rate Scraper

on:
  schedule:
    - cron: "30 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✅ install Chrome for Selenium
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # ✅ install python packages
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pdfplumber selenium webdriver-manager lxml

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "fd-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add fd_rates.json
          git commit -m "Auto update FD rates" || echo "No changes"
          git push
